import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AnimateCursor } from "@/shared/components";
import { Footer, Header } from "@/widgets";

const polonium_regular = localFont({
	src: "./fonts/PoloniumRegular.woff2",
	variable: "--font-polonium",
	weight: "400",
});

const polonium_bold = localFont({
	src: "./fonts/PoloniumBold.woff2",
	variable: "--font-polonium",
	weight: "700",
});

export const metadata: Metadata = {
	title: "Портфолио",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${polonium_regular.variable} antialiased flex flex-col min-h-dvh`}>
				<Header />
				{children}
				<Footer />
				<AnimateCursor />
			</body>
		</html>
	);
}
